import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Hero from "./components/Hero";
import Slider from "./components/Slider";
import { SliderData } from "./components/SliderData";
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Oracula Generator</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero
        heading="Oracula Generator"
        subheading="Create your own repository of wisdom."
      />
      <Slider slides={SliderData} />
    </div>
  );
}
